{
    'name': 'SDM Trip Management',
    'version': '17.0.0.0',
    'category': 'Fleet',
    'author': 'Sidmec Technologies',
    'website': '',
    'depends': ['base', 'sale', 'crm', 'purchase_stock', 'stock', 'hr', 'fleet', 'sdm_additional_fields',
                'om_account_asset','product'],
    'data': [
        'reports/ticket_report.xml',
        'reports/report_trip_ticket.xml',
        'security/ir.model.access.csv',
        'data/seq_trip_management.xml',
        'data/alert_email_template.xml',
        'views/trip_management_views.xml',
        'views/driver_list_view.xml',
        'views/trip_ticket_dashboard_views.xml',
        'views/trip_ticket_views.xml',
        'views/driver_profile_views.xml',
        'views/driver_assignment_views.xml',
        'views/driver_menu.xml',
        'views/fleet_vehicle.xml',
    ],
    'installable': True,
    'auto_install': False,
    'license': 'LGPL-3',
}
